CREATE TABLE properties (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  listing_type ENUM('sale','rent') NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(14,2) NOT NULL,
  currency CHAR(3) DEFAULT 'USD' NOT NULL,
  price_period ENUM('monthly','weekly','daily','yearly','one_time'),
  bedrooms SMALLINT UNSIGNED,
  bathrooms SMALLINT UNSIGNED,
  rooms SMALLINT UNSIGNED,
  floors SMALLINT UNSIGNED,
  area DECIMAL(10,2),
  state_id INT NOT NULL,
  city_id INT NOT NULL,
  neighborhood_id INT,
  owner_id INT,
  agent_id INT,
  status VARCHAR(30) DEFAULT 'available',
  location_lat DOUBLE,
  location_lng DOUBLE,
  location POINT,
  published_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT(1) DEFAULT 0,
  SPATIAL INDEX(location)
);
