spring.application.name=frontend
server.port=8081
debug=true
external.api.properties-url=http://localhost:8080/api/properties

# i18n configuration
spring.messages.basename=messages
spring.web.locale=ar_SA
spring.web.locale-resolver=fixed
